[project]
name = "uv-biotite-issue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "biotite>=1.2.0",
    "bpy>=4.4.0",
    "jupyter>=1.1.1",
    "molecularnodes>=4.4.1",
    "pytest>=8.3.5",
]
