name: example-run

on: 
    push:
      branches: ["main"]
    
jobs:
    bpy:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 8
            fail-fast: false
            matrix:
              version: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
              os: [ubuntu-latest, macos-14, windows-latest]
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v5
            - name: Run Tests "not density"
              run: |
                uv run example.py